// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fury/vbr/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgIncrementBlockRewardsPool struct {
	Funder string                                   `protobuf:"bytes,1,opt,name=funder,proto3" json:"funder,omitempty" yaml:"funder"`
	Amount github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,2,rep,name=amount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"amount" yaml:"amount"`
}

func (m *MsgIncrementBlockRewardsPool) Reset()         { *m = MsgIncrementBlockRewardsPool{} }
func (m *MsgIncrementBlockRewardsPool) String() string { return proto.CompactTextString(m) }
func (*MsgIncrementBlockRewardsPool) ProtoMessage()    {}
func (*MsgIncrementBlockRewardsPool) Descriptor() ([]byte, []int) {
	return fileDescriptor_eba84e9cc76fdf40, []int{0}
}
func (m *MsgIncrementBlockRewardsPool) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIncrementBlockRewardsPool) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIncrementBlockRewardsPool.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIncrementBlockRewardsPool) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIncrementBlockRewardsPool.Merge(m, src)
}
func (m *MsgIncrementBlockRewardsPool) XXX_Size() int {
	return m.Size()
}
func (m *MsgIncrementBlockRewardsPool) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIncrementBlockRewardsPool.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIncrementBlockRewardsPool proto.InternalMessageInfo

func (m *MsgIncrementBlockRewardsPool) GetFunder() string {
	if m != nil {
		return m.Funder
	}
	return ""
}

func (m *MsgIncrementBlockRewardsPool) GetAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Amount
	}
	return nil
}

type MsgIncrementBlockRewardsPoolResponse struct {
}

func (m *MsgIncrementBlockRewardsPoolResponse) Reset()         { *m = MsgIncrementBlockRewardsPoolResponse{} }
func (m *MsgIncrementBlockRewardsPoolResponse) String() string { return proto.CompactTextString(m) }
func (*MsgIncrementBlockRewardsPoolResponse) ProtoMessage()    {}
func (*MsgIncrementBlockRewardsPoolResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eba84e9cc76fdf40, []int{1}
}
func (m *MsgIncrementBlockRewardsPoolResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgIncrementBlockRewardsPoolResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgIncrementBlockRewardsPoolResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgIncrementBlockRewardsPoolResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgIncrementBlockRewardsPoolResponse.Merge(m, src)
}
func (m *MsgIncrementBlockRewardsPoolResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgIncrementBlockRewardsPoolResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgIncrementBlockRewardsPoolResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgIncrementBlockRewardsPoolResponse proto.InternalMessageInfo

type MsgSetParams struct {
	Government           string                                 `protobuf:"bytes,1,opt,name=Government,proto3" json:"Government,omitempty" yaml:"government"`
	DistrEpochIdentifier string                                 `protobuf:"bytes,2,opt,name=distr_epoch_identifier,json=distrEpochIdentifier,proto3" json:"distr_epoch_identifier,omitempty" yaml:"distr_epoch_identifier"`
	EarnRate             github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=earn_rate,json=earnRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"earn_rate" yaml:"earn_rate"`
}

func (m *MsgSetParams) Reset()         { *m = MsgSetParams{} }
func (m *MsgSetParams) String() string { return proto.CompactTextString(m) }
func (*MsgSetParams) ProtoMessage()    {}
func (*MsgSetParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_eba84e9cc76fdf40, []int{2}
}
func (m *MsgSetParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetParams.Merge(m, src)
}
func (m *MsgSetParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetParams proto.InternalMessageInfo

func (m *MsgSetParams) GetGovernment() string {
	if m != nil {
		return m.Government
	}
	return ""
}

func (m *MsgSetParams) GetDistrEpochIdentifier() string {
	if m != nil {
		return m.DistrEpochIdentifier
	}
	return ""
}

type MsgSetParamsResponse struct {
}

func (m *MsgSetParamsResponse) Reset()         { *m = MsgSetParamsResponse{} }
func (m *MsgSetParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetParamsResponse) ProtoMessage()    {}
func (*MsgSetParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_eba84e9cc76fdf40, []int{3}
}
func (m *MsgSetParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetParamsResponse.Merge(m, src)
}
func (m *MsgSetParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetParamsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgIncrementBlockRewardsPool)(nil), "tessornetwork.fury.vbr.MsgIncrementBlockRewardsPool")
	proto.RegisterType((*MsgIncrementBlockRewardsPoolResponse)(nil), "tessornetwork.fury.vbr.MsgIncrementBlockRewardsPoolResponse")
	proto.RegisterType((*MsgSetParams)(nil), "tessornetwork.fury.vbr.MsgSetParams")
	proto.RegisterType((*MsgSetParamsResponse)(nil), "tessornetwork.fury.vbr.MsgSetParamsResponse")
}

func init() { proto.RegisterFile("fury/vbr/tx.proto", fileDescriptor_eba84e9cc76fdf40) }

var fileDescriptor_eba84e9cc76fdf40 = []byte{
	// 497 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xcf, 0x6e, 0xd3, 0x4e,
	0x10, 0x8e, 0x1b, 0x29, 0xfa, 0x75, 0x7f, 0x20, 0x11, 0x2b, 0x44, 0x69, 0x04, 0x76, 0xb1, 0xaa,
	0x2a, 0x95, 0x60, 0xad, 0x16, 0xb8, 0x20, 0x2e, 0xb8, 0x20, 0xd4, 0x43, 0xa4, 0xca, 0x1c, 0x90,
	0xb8, 0x44, 0xfe, 0x33, 0x71, 0xad, 0xc4, 0x3b, 0xd1, 0xee, 0x26, 0x6d, 0x9e, 0x02, 0x9e, 0x83,
	0x97, 0xe0, 0xda, 0x63, 0x8f, 0x88, 0x83, 0x41, 0xc9, 0x1b, 0xe4, 0xc4, 0x0d, 0xb4, 0x5e, 0x27,
	0x0d, 0x52, 0x89, 0x2a, 0x4e, 0x1e, 0xcd, 0x7c, 0xf3, 0x7d, 0xb3, 0x9f, 0x67, 0x48, 0xbd, 0x3f,
	0xe6, 0x53, 0x77, 0x12, 0x72, 0x57, 0x5e, 0xd0, 0x11, 0x47, 0x89, 0x66, 0x53, 0x82, 0x10, 0xc8,
	0x19, 0xc8, 0x73, 0xe4, 0x03, 0xaa, 0x00, 0x74, 0x12, 0xf2, 0x76, 0x23, 0xc1, 0x04, 0x0b, 0x88,
	0xab, 0x22, 0x8d, 0x6e, 0x5b, 0x11, 0x8a, 0x0c, 0x85, 0x1b, 0x06, 0x02, 0xdc, 0xc9, 0x61, 0x08,
	0x32, 0x38, 0x74, 0x23, 0x4c, 0x99, 0xae, 0x3b, 0x5f, 0x0c, 0xf2, 0xa0, 0x2b, 0x92, 0x13, 0x16,
	0x71, 0xc8, 0x80, 0x49, 0x6f, 0x88, 0xd1, 0xc0, 0x87, 0xf3, 0x80, 0xc7, 0xe2, 0x14, 0x71, 0x68,
	0x1e, 0x90, 0x5a, 0x7f, 0xcc, 0x62, 0xe0, 0x2d, 0x63, 0xd7, 0xe8, 0x6c, 0x7b, 0xf5, 0x45, 0x6e,
	0xdf, 0x9d, 0x06, 0xd9, 0xf0, 0x85, 0xa3, 0xf3, 0x8e, 0x5f, 0x02, 0x4c, 0x49, 0x6a, 0x41, 0x86,
	0x63, 0x26, 0x5b, 0x5b, 0xbb, 0xd5, 0xce, 0xff, 0x47, 0x3b, 0x54, 0x8b, 0x53, 0x25, 0x4e, 0x4b,
	0x71, 0x7a, 0x8c, 0x29, 0xf3, 0x5e, 0x5d, 0xe6, 0x76, 0xe5, 0x9a, 0x49, 0xb7, 0x39, 0x9f, 0xbf,
	0xdb, 0x9d, 0x24, 0x95, 0x67, 0xe3, 0x90, 0x46, 0x98, 0xb9, 0xe5, 0xe8, 0xfa, 0xf3, 0x44, 0xc4,
	0x03, 0x57, 0x4e, 0x47, 0x20, 0x0a, 0x06, 0xe1, 0x97, 0x5a, 0xce, 0x3e, 0xd9, 0xdb, 0xf4, 0x00,
	0x1f, 0xc4, 0x08, 0x99, 0x00, 0xe7, 0x97, 0x41, 0xee, 0x74, 0x45, 0xf2, 0x0e, 0xe4, 0x69, 0xc0,
	0x83, 0x4c, 0x98, 0xcf, 0x09, 0x79, 0x8b, 0x13, 0xe0, 0x4c, 0xb5, 0x95, 0xaf, 0xbb, 0xbf, 0xc8,
	0xed, 0xba, 0x9e, 0x29, 0x59, 0xd5, 0x1c, 0x7f, 0x0d, 0x68, 0xbe, 0x27, 0xcd, 0x38, 0x15, 0x92,
	0xf7, 0x60, 0x84, 0xd1, 0x59, 0x2f, 0x8d, 0x81, 0xc9, 0xb4, 0x9f, 0x02, 0x6f, 0x6d, 0x15, 0x14,
	0x8f, 0x16, 0xb9, 0xfd, 0x50, 0x53, 0xdc, 0x8c, 0x73, 0xfc, 0x46, 0x51, 0x78, 0xa3, 0xf2, 0x27,
	0xab, 0xb4, 0xd9, 0x23, 0xdb, 0x10, 0x70, 0xd6, 0xe3, 0x81, 0x84, 0x56, 0xb5, 0xe0, 0xf2, 0x94,
	0x4d, 0xdf, 0x72, 0x7b, 0xff, 0x16, 0xae, 0xbc, 0x86, 0x68, 0x91, 0xdb, 0xf7, 0xb4, 0xf2, 0x8a,
	0xc8, 0xf1, 0xff, 0x53, 0xb1, 0xaf, 0xc2, 0x26, 0x69, 0xac, 0x1b, 0xb0, 0x74, 0xe6, 0xe8, 0xa7,
	0x41, 0xaa, 0x5d, 0x91, 0x98, 0x1f, 0x0d, 0xb2, 0xf3, 0xf7, 0x45, 0x78, 0x46, 0x6f, 0x5e, 0x3c,
	0xba, 0xc9, 0xfd, 0xf6, 0xcb, 0x7f, 0xe9, 0x5a, 0x4e, 0xa6, 0x2c, 0xb9, 0xfe, 0x5f, 0x7b, 0x1b,
	0xa8, 0x56, 0xa8, 0xf6, 0xe3, 0xdb, 0xa0, 0x96, 0x02, 0xde, 0xf1, 0xe5, 0xcc, 0x32, 0xae, 0x66,
	0x96, 0xf1, 0x63, 0x66, 0x19, 0x9f, 0xe6, 0x56, 0xe5, 0x6a, 0x6e, 0x55, 0xbe, 0xce, 0xad, 0xca,
	0x87, 0x83, 0x35, 0xcb, 0xff, 0x60, 0x74, 0x8b, 0x93, 0xbc, 0xd0, 0x47, 0xa9, 0x9c, 0x0f, 0x6b,
	0xc5, 0x29, 0x3d, 0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x7d, 0x6d, 0x06, 0x1c, 0xad, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	IncrementBlockRewardsPool(ctx context.Context, in *MsgIncrementBlockRewardsPool, opts ...grpc.CallOption) (*MsgIncrementBlockRewardsPoolResponse, error)
	SetParams(ctx context.Context, in *MsgSetParams, opts ...grpc.CallOption) (*MsgSetParamsResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) IncrementBlockRewardsPool(ctx context.Context, in *MsgIncrementBlockRewardsPool, opts ...grpc.CallOption) (*MsgIncrementBlockRewardsPoolResponse, error) {
	out := new(MsgIncrementBlockRewardsPoolResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.vbr.Msg/IncrementBlockRewardsPool", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetParams(ctx context.Context, in *MsgSetParams, opts ...grpc.CallOption) (*MsgSetParamsResponse, error) {
	out := new(MsgSetParamsResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.vbr.Msg/SetParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	IncrementBlockRewardsPool(context.Context, *MsgIncrementBlockRewardsPool) (*MsgIncrementBlockRewardsPoolResponse, error)
	SetParams(context.Context, *MsgSetParams) (*MsgSetParamsResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) IncrementBlockRewardsPool(ctx context.Context, req *MsgIncrementBlockRewardsPool) (*MsgIncrementBlockRewardsPoolResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IncrementBlockRewardsPool not implemented")
}
func (*UnimplementedMsgServer) SetParams(ctx context.Context, req *MsgSetParams) (*MsgSetParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetParams not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_IncrementBlockRewardsPool_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgIncrementBlockRewardsPool)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).IncrementBlockRewardsPool(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.vbr.Msg/IncrementBlockRewardsPool",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).IncrementBlockRewardsPool(ctx, req.(*MsgIncrementBlockRewardsPool))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.vbr.Msg/SetParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetParams(ctx, req.(*MsgSetParams))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tessornetwork.fury.vbr.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IncrementBlockRewardsPool",
			Handler:    _Msg_IncrementBlockRewardsPool_Handler,
		},
		{
			MethodName: "SetParams",
			Handler:    _Msg_SetParams_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fury/vbr/tx.proto",
}

func (m *MsgIncrementBlockRewardsPool) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIncrementBlockRewardsPool) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIncrementBlockRewardsPool) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Amount) > 0 {
		for iNdEx := len(m.Amount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Amount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Funder) > 0 {
		i -= len(m.Funder)
		copy(dAtA[i:], m.Funder)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Funder)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgIncrementBlockRewardsPoolResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgIncrementBlockRewardsPoolResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgIncrementBlockRewardsPoolResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.EarnRate.Size()
		i -= size
		if _, err := m.EarnRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.DistrEpochIdentifier) > 0 {
		i -= len(m.DistrEpochIdentifier)
		copy(dAtA[i:], m.DistrEpochIdentifier)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DistrEpochIdentifier)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Government) > 0 {
		i -= len(m.Government)
		copy(dAtA[i:], m.Government)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Government)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgIncrementBlockRewardsPool) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Funder)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Amount) > 0 {
		for _, e := range m.Amount {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	return n
}

func (m *MsgIncrementBlockRewardsPoolResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Government)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DistrEpochIdentifier)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.EarnRate.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgSetParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgIncrementBlockRewardsPool) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIncrementBlockRewardsPool: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIncrementBlockRewardsPool: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Funder", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Funder = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Amount = append(m.Amount, types.Coin{})
			if err := m.Amount[len(m.Amount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgIncrementBlockRewardsPoolResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgIncrementBlockRewardsPoolResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgIncrementBlockRewardsPoolResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Government", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Government = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DistrEpochIdentifier", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DistrEpochIdentifier = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EarnRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.EarnRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
