version: 1
accounts:
- name: alice
  coins:
  - 20000000000ufusd
  - 200000000000ufury
  mnemonic: gaze apart pen defense tomorrow index again pool earth force napkin noble
    elevator payment hawk trip cute gown fade wear swallow alert lemon people
- name: bob
  coins:
  - 10000000000ufusd
  - 100000000000ufury
  mnemonic: special chest leaf section reunion inflict busy blouse inflict kid alcohol
    hazard embody mosquito green turkey street very lab forest gain disease hollow
    bomb
- name: gov
  coins:
  - 10000000000ufusd
  - 100000000000ufury
  mnemonic: bonus raccoon material jump tired under cup senior wash peace cook mansion
    nice rely outside atom surface maid dune poet hold forum electric accuse
faucet:
  name: bob
  coins:
  - 5ufusd
  - 100000ufury
client:
  typescript:
    path: ts-client
  vuex:
    path: vue/src/store
  hooks:
    path: react/src/hooks
  openapi:
    path: docs_3_0/static/openapi.yml
genesis:
  app_state:
    crisis:
      constant_fee:
        denom: ufury
    furykyc:
      liquidity_pool_amount:
      - amount: "1000000000000"
        denom: ufury
      memberships:
      - expiry_at: "2022-03-21T00:00:00Z"
        membership_type: black
        owner: did:fury:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm
        tsp_address: did:fury:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm
      trusted_service_providers:
      - did:fury:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm
    furymint:
      Positions:
      - ID: 090ca0c2-cf00-4119-8307-b51413a00cf4
        collateral: "7"
        created_at: "2021-07-22T13:18:44.598560074Z"
        credits:
          amount: "10"
          denom: ufusd
        exchange_rate: "0.610000000000000000"
        owner: did:fury:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm
      params:
        conversion_rate: "0.610000000000000000"
        freeze_period: 1814400s
    gov:
      deposit_params:
        min_deposit:
        - amount: "10000000"
          denom: ufury
      voting_params:
        voting_period: 120s
    government:
      governmentAddress: did:fury:1zg4jreq2g57s4efrl7wnh2swtrz3jt9nfaumcm
    staking:
      params:
        bond_denom: ufury
    vbr:
      params:
        distr_epoch_identifier: minute
        earn_rate: "0.500000000000000000"
      poolAmount:
      - amount: "10000000.000000000000000000"
        denom: ufury
validators: []
