version: '3'

services:
  furynode0:
    container_name: furynode0
    image: "tessornetwork/furynode"
    ports:
      - "26656-26657:26656-26657"
      - "1317:1317"
      - "9090:9090"
    environment:
      - ID=0
      - LOG=${LOG:-fury.log}
    volumes:
      - ./build:/fury:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.2

  furynode1:
    container_name: furynode1
    image: "tessornetwork/furynode"
    ports:
      - "26659-26660:26656-26657"
      - "9091:9090"
    environment:
      - ID=1
      - LOG=${LOG:-fury.log}
      - TZ=Asia/Colombo
    volumes:
      - ./build:/fury:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.3

  furynode2:
    container_name: furynode2
    image: "tessornetwork/furynode"
    environment:
      - ID=2
      - LOG=${LOG:-fury.log}
    ports:
      - "26661-26662:26656-26657"
      - "9092:9090"
    volumes:
      - ./build:/fury:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.4

  furynode3:
    container_name: furynode3
    image: "tessornetwork/furynode"
    environment:
      - ID=3
      - LOG=${LOG:-fury.log}
    ports:
      - "26663-26664:26656-26657"
      - "9093:9090"
    volumes:
      - ./build:/fury:Z
    networks:
      localnet:
        ipv4_address: 192.168.10.5


  proxy-nginx:
    container_name:   proxy-nginx
    image: "nginx"
    ports:
      - "7123:7123"
      - "7124:7124"
      - "7125:7125"
    volumes:
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - localnet

networks:
  localnet:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 192.168.10.0/16
