// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fury/documents/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgShareDocument struct {
	Sender         string                  `protobuf:"bytes,1,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipients     []string                `protobuf:"bytes,2,rep,name=recipients,proto3" json:"recipients,omitempty"`
	UUID           string                  `protobuf:"bytes,3,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Metadata       *DocumentMetadata       `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	ContentURI     string                  `protobuf:"bytes,5,opt,name=contentURI,proto3" json:"contentURI,omitempty"`
	Checksum       *DocumentChecksum       `protobuf:"bytes,6,opt,name=checksum,proto3" json:"checksum,omitempty"`
	EncryptionData *DocumentEncryptionData `protobuf:"bytes,7,opt,name=encryptionData,proto3" json:"encryptionData,omitempty"`
	DoSign         *DocumentDoSign         `protobuf:"bytes,8,opt,name=doSign,proto3" json:"doSign,omitempty"`
}

func (m *MsgShareDocument) Reset()         { *m = MsgShareDocument{} }
func (m *MsgShareDocument) String() string { return proto.CompactTextString(m) }
func (*MsgShareDocument) ProtoMessage()    {}
func (*MsgShareDocument) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2c3dee8a9b13723, []int{0}
}
func (m *MsgShareDocument) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgShareDocument) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgShareDocument.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgShareDocument) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgShareDocument.Merge(m, src)
}
func (m *MsgShareDocument) XXX_Size() int {
	return m.Size()
}
func (m *MsgShareDocument) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgShareDocument.DiscardUnknown(m)
}

var xxx_messageInfo_MsgShareDocument proto.InternalMessageInfo

func (m *MsgShareDocument) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgShareDocument) GetRecipients() []string {
	if m != nil {
		return m.Recipients
	}
	return nil
}

func (m *MsgShareDocument) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *MsgShareDocument) GetMetadata() *DocumentMetadata {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func (m *MsgShareDocument) GetContentURI() string {
	if m != nil {
		return m.ContentURI
	}
	return ""
}

func (m *MsgShareDocument) GetChecksum() *DocumentChecksum {
	if m != nil {
		return m.Checksum
	}
	return nil
}

func (m *MsgShareDocument) GetEncryptionData() *DocumentEncryptionData {
	if m != nil {
		return m.EncryptionData
	}
	return nil
}

func (m *MsgShareDocument) GetDoSign() *DocumentDoSign {
	if m != nil {
		return m.DoSign
	}
	return nil
}

type MsgShareDocumentResponse struct {
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (m *MsgShareDocumentResponse) Reset()         { *m = MsgShareDocumentResponse{} }
func (m *MsgShareDocumentResponse) String() string { return proto.CompactTextString(m) }
func (*MsgShareDocumentResponse) ProtoMessage()    {}
func (*MsgShareDocumentResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2c3dee8a9b13723, []int{1}
}
func (m *MsgShareDocumentResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgShareDocumentResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgShareDocumentResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgShareDocumentResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgShareDocumentResponse.Merge(m, src)
}
func (m *MsgShareDocumentResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgShareDocumentResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgShareDocumentResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgShareDocumentResponse proto.InternalMessageInfo

func (m *MsgShareDocumentResponse) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

type MsgSendDocumentReceipt struct {
	UUID         string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Sender       string `protobuf:"bytes,2,opt,name=sender,proto3" json:"sender,omitempty"`
	Recipient    string `protobuf:"bytes,3,opt,name=recipient,proto3" json:"recipient,omitempty"`
	TxHash       string `protobuf:"bytes,4,opt,name=txHash,proto3" json:"txHash,omitempty"`
	DocumentUUID string `protobuf:"bytes,5,opt,name=DocumentUUID,proto3" json:"DocumentUUID,omitempty"`
	Proof        string `protobuf:"bytes,6,opt,name=proof,proto3" json:"proof,omitempty"`
}

func (m *MsgSendDocumentReceipt) Reset()         { *m = MsgSendDocumentReceipt{} }
func (m *MsgSendDocumentReceipt) String() string { return proto.CompactTextString(m) }
func (*MsgSendDocumentReceipt) ProtoMessage()    {}
func (*MsgSendDocumentReceipt) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2c3dee8a9b13723, []int{2}
}
func (m *MsgSendDocumentReceipt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendDocumentReceipt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendDocumentReceipt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendDocumentReceipt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendDocumentReceipt.Merge(m, src)
}
func (m *MsgSendDocumentReceipt) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendDocumentReceipt) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendDocumentReceipt.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendDocumentReceipt proto.InternalMessageInfo

func (m *MsgSendDocumentReceipt) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func (m *MsgSendDocumentReceipt) GetSender() string {
	if m != nil {
		return m.Sender
	}
	return ""
}

func (m *MsgSendDocumentReceipt) GetRecipient() string {
	if m != nil {
		return m.Recipient
	}
	return ""
}

func (m *MsgSendDocumentReceipt) GetTxHash() string {
	if m != nil {
		return m.TxHash
	}
	return ""
}

func (m *MsgSendDocumentReceipt) GetDocumentUUID() string {
	if m != nil {
		return m.DocumentUUID
	}
	return ""
}

func (m *MsgSendDocumentReceipt) GetProof() string {
	if m != nil {
		return m.Proof
	}
	return ""
}

type MsgSendDocumentReceiptResponse struct {
	UUID string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
}

func (m *MsgSendDocumentReceiptResponse) Reset()         { *m = MsgSendDocumentReceiptResponse{} }
func (m *MsgSendDocumentReceiptResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSendDocumentReceiptResponse) ProtoMessage()    {}
func (*MsgSendDocumentReceiptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_d2c3dee8a9b13723, []int{3}
}
func (m *MsgSendDocumentReceiptResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSendDocumentReceiptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSendDocumentReceiptResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSendDocumentReceiptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSendDocumentReceiptResponse.Merge(m, src)
}
func (m *MsgSendDocumentReceiptResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSendDocumentReceiptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSendDocumentReceiptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSendDocumentReceiptResponse proto.InternalMessageInfo

func (m *MsgSendDocumentReceiptResponse) GetUUID() string {
	if m != nil {
		return m.UUID
	}
	return ""
}

func init() {
	proto.RegisterType((*MsgShareDocument)(nil), "tessornetwork.fury.documents.MsgShareDocument")
	proto.RegisterType((*MsgShareDocumentResponse)(nil), "tessornetwork.fury.documents.MsgShareDocumentResponse")
	proto.RegisterType((*MsgSendDocumentReceipt)(nil), "tessornetwork.fury.documents.MsgSendDocumentReceipt")
	proto.RegisterType((*MsgSendDocumentReceiptResponse)(nil), "tessornetwork.fury.documents.MsgSendDocumentReceiptResponse")
}

func init() { proto.RegisterFile("fury/documents/tx.proto", fileDescriptor_d2c3dee8a9b13723) }

var fileDescriptor_d2c3dee8a9b13723 = []byte{
	// 502 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x4f, 0x8b, 0xd3, 0x40,
	0x14, 0x6f, 0xda, 0xdd, 0xba, 0x7d, 0xfe, 0x41, 0x46, 0x59, 0x43, 0x59, 0x43, 0x89, 0x08, 0x05,
	0x25, 0x81, 0xb5, 0x78, 0xf2, 0xa4, 0x11, 0xac, 0xd0, 0xcb, 0x94, 0x5e, 0xc4, 0x4b, 0x76, 0x32,
	0xdb, 0x84, 0x25, 0x33, 0x61, 0x66, 0xca, 0xb6, 0x1f, 0x41, 0x4f, 0x7e, 0x18, 0x4f, 0x7e, 0x02,
	0x8f, 0x7b, 0xf4, 0x28, 0xed, 0x17, 0x91, 0x4c, 0xfe, 0xb4, 0x89, 0xed, 0x76, 0x77, 0x6f, 0x99,
	0x97, 0xdf, 0x9f, 0x37, 0xef, 0xf7, 0x18, 0x78, 0x76, 0x3e, 0x13, 0x0b, 0x37, 0xe0, 0x64, 0x16,
	0x53, 0xa6, 0xa4, 0xab, 0xe6, 0x4e, 0x22, 0xb8, 0xe2, 0xe8, 0x44, 0x51, 0x29, 0xb9, 0x60, 0x54,
	0x5d, 0x72, 0x71, 0xe1, 0xa4, 0x30, 0xa7, 0x84, 0x75, 0x9f, 0xd7, 0x68, 0xc5, 0x57, 0x46, 0xee,
	0xbe, 0xd8, 0xf1, 0xdb, 0xe3, 0xe3, 0x68, 0xca, 0x72, 0xd0, 0xab, 0x1d, 0xa0, 0x8f, 0x8c, 0x88,
	0x45, 0xa2, 0x22, 0xce, 0x3c, 0x5f, 0xf9, 0x7b, 0xc0, 0x23, 0xaa, 0xfc, 0xc0, 0x57, 0xfe, 0x98,
	0x84, 0x34, 0x2e, 0xc0, 0x2f, 0x77, 0x80, 0x3f, 0x84, 0x94, 0x5c, 0xc8, 0x59, 0x9c, 0xc1, 0xec,
	0x5f, 0x2d, 0x78, 0x3c, 0x92, 0xd3, 0x71, 0xe8, 0x0b, 0xea, 0xe5, 0x10, 0x74, 0x0c, 0x6d, 0x49,
	0x59, 0x40, 0x85, 0x69, 0xf4, 0x8c, 0x7e, 0x07, 0xe7, 0x27, 0x64, 0x01, 0x08, 0x4a, 0xa2, 0x24,
	0x4a, 0x15, 0xcd, 0x66, 0xaf, 0xd5, 0xef, 0xe0, 0x8d, 0x0a, 0x42, 0x70, 0x30, 0x99, 0x0c, 0x3d,
	0xb3, 0xa5, 0x59, 0xfa, 0x1b, 0x7d, 0x86, 0xa3, 0x38, 0xef, 0xcf, 0x3c, 0xe8, 0x19, 0xfd, 0xfb,
	0xa7, 0x8e, 0x73, 0xdd, 0x58, 0x1d, 0xaf, 0x76, 0x2b, 0x5c, 0xf2, 0x53, 0x7f, 0xc2, 0x99, 0xa2,
	0x4c, 0x4d, 0xf0, 0xd0, 0x3c, 0xd4, 0x2e, 0x1b, 0x95, 0xd4, 0x8b, 0xe4, 0xd7, 0x33, 0xdb, 0xb7,
	0xf1, 0x2a, 0x86, 0x82, 0x4b, 0x3e, 0xfa, 0x0a, 0x8f, 0x68, 0x25, 0x04, 0xf3, 0x9e, 0x56, 0x1c,
	0xdc, 0x4c, 0xb1, 0x1a, 0x20, 0xae, 0x69, 0x21, 0x0f, 0xda, 0x81, 0xde, 0x03, 0xf3, 0x48, 0xab,
	0xbe, 0xbe, 0x99, 0x6a, 0xb6, 0x3b, 0x38, 0xe7, 0xda, 0x0e, 0x98, 0xf5, 0xec, 0x30, 0x95, 0x09,
	0x67, 0x92, 0x96, 0x59, 0x18, 0xeb, 0x2c, 0xec, 0x9f, 0x06, 0x1c, 0xa7, 0x04, 0xca, 0x82, 0x35,
	0x9e, 0xd0, 0x28, 0x51, 0xdb, 0xe0, 0x1b, 0x6b, 0xd0, 0xac, 0xac, 0xc1, 0x09, 0x74, 0xca, 0xd0,
	0xf3, 0xac, 0xd7, 0x85, 0x94, 0xa5, 0xe6, 0x9f, 0x7c, 0x19, 0xea, 0xb8, 0x3b, 0x38, 0x3f, 0x21,
	0x1b, 0x1e, 0x14, 0xa6, 0xda, 0x29, 0x8b, 0xaf, 0x52, 0x43, 0x4f, 0xe1, 0x30, 0x11, 0x9c, 0x9f,
	0xeb, 0xf4, 0x3a, 0x38, 0x3b, 0xd8, 0x03, 0xb0, 0xb6, 0x77, 0x7d, 0xdd, 0x65, 0x4f, 0xbf, 0x37,
	0xa1, 0x35, 0x92, 0x53, 0x74, 0x09, 0x0f, 0xab, 0xdb, 0xbd, 0x67, 0x27, 0xea, 0x13, 0xed, 0xbe,
	0xbd, 0x1d, 0xbe, 0x6c, 0xea, 0x9b, 0x01, 0x4f, 0xb6, 0x8d, 0x7a, 0xb0, 0x5f, 0xef, 0x7f, 0x56,
	0xf7, 0xdd, 0x5d, 0x58, 0x45, 0x2f, 0xef, 0x87, 0xbf, 0x97, 0x96, 0x71, 0xb5, 0xb4, 0x8c, 0xbf,
	0x4b, 0xcb, 0xf8, 0xb1, 0xb2, 0x1a, 0x57, 0x2b, 0xab, 0xf1, 0x67, 0x65, 0x35, 0xbe, 0xb8, 0xd3,
	0x48, 0x85, 0xb3, 0x33, 0x87, 0xf0, 0xd8, 0xad, 0x38, 0xb8, 0xfa, 0x01, 0x99, 0x6f, 0xbe, 0x8b,
	0x8b, 0x84, 0xca, 0xb3, 0xb6, 0x7e, 0x38, 0xde, 0xfc, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x17, 0xd0,
	0x16, 0x47, 0x36, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	ShareDocument(ctx context.Context, in *MsgShareDocument, opts ...grpc.CallOption) (*MsgShareDocumentResponse, error)
	SendDocumentReceipt(ctx context.Context, in *MsgSendDocumentReceipt, opts ...grpc.CallOption) (*MsgSendDocumentReceiptResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) ShareDocument(ctx context.Context, in *MsgShareDocument, opts ...grpc.CallOption) (*MsgShareDocumentResponse, error) {
	out := new(MsgShareDocumentResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.documents.Msg/ShareDocument", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SendDocumentReceipt(ctx context.Context, in *MsgSendDocumentReceipt, opts ...grpc.CallOption) (*MsgSendDocumentReceiptResponse, error) {
	out := new(MsgSendDocumentReceiptResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.documents.Msg/SendDocumentReceipt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	ShareDocument(context.Context, *MsgShareDocument) (*MsgShareDocumentResponse, error)
	SendDocumentReceipt(context.Context, *MsgSendDocumentReceipt) (*MsgSendDocumentReceiptResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) ShareDocument(ctx context.Context, req *MsgShareDocument) (*MsgShareDocumentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareDocument not implemented")
}
func (*UnimplementedMsgServer) SendDocumentReceipt(ctx context.Context, req *MsgSendDocumentReceipt) (*MsgSendDocumentReceiptResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendDocumentReceipt not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_ShareDocument_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgShareDocument)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).ShareDocument(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.documents.Msg/ShareDocument",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).ShareDocument(ctx, req.(*MsgShareDocument))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SendDocumentReceipt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSendDocumentReceipt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SendDocumentReceipt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.documents.Msg/SendDocumentReceipt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SendDocumentReceipt(ctx, req.(*MsgSendDocumentReceipt))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tessornetwork.fury.documents.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ShareDocument",
			Handler:    _Msg_ShareDocument_Handler,
		},
		{
			MethodName: "SendDocumentReceipt",
			Handler:    _Msg_SendDocumentReceipt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fury/documents/tx.proto",
}

func (m *MsgShareDocument) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgShareDocument) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgShareDocument) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.DoSign != nil {
		{
			size, err := m.DoSign.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x42
	}
	if m.EncryptionData != nil {
		{
			size, err := m.EncryptionData.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x3a
	}
	if m.Checksum != nil {
		{
			size, err := m.Checksum.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x32
	}
	if len(m.ContentURI) > 0 {
		i -= len(m.ContentURI)
		copy(dAtA[i:], m.ContentURI)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ContentURI)))
		i--
		dAtA[i] = 0x2a
	}
	if m.Metadata != nil {
		{
			size, err := m.Metadata.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if len(m.UUID) > 0 {
		i -= len(m.UUID)
		copy(dAtA[i:], m.UUID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UUID)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Recipients) > 0 {
		for iNdEx := len(m.Recipients) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Recipients[iNdEx])
			copy(dAtA[i:], m.Recipients[iNdEx])
			i = encodeVarintTx(dAtA, i, uint64(len(m.Recipients[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgShareDocumentResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgShareDocumentResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgShareDocumentResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UUID) > 0 {
		i -= len(m.UUID)
		copy(dAtA[i:], m.UUID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UUID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendDocumentReceipt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendDocumentReceipt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendDocumentReceipt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Proof) > 0 {
		i -= len(m.Proof)
		copy(dAtA[i:], m.Proof)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Proof)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.DocumentUUID) > 0 {
		i -= len(m.DocumentUUID)
		copy(dAtA[i:], m.DocumentUUID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.DocumentUUID)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.TxHash) > 0 {
		i -= len(m.TxHash)
		copy(dAtA[i:], m.TxHash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxHash)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.Recipient) > 0 {
		i -= len(m.Recipient)
		copy(dAtA[i:], m.Recipient)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Recipient)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Sender) > 0 {
		i -= len(m.Sender)
		copy(dAtA[i:], m.Sender)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Sender)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.UUID) > 0 {
		i -= len(m.UUID)
		copy(dAtA[i:], m.UUID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UUID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSendDocumentReceiptResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSendDocumentReceiptResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSendDocumentReceiptResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.UUID) > 0 {
		i -= len(m.UUID)
		copy(dAtA[i:], m.UUID)
		i = encodeVarintTx(dAtA, i, uint64(len(m.UUID)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgShareDocument) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.Recipients) > 0 {
		for _, s := range m.Recipients {
			l = len(s)
			n += 1 + l + sovTx(uint64(l))
		}
	}
	l = len(m.UUID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Metadata != nil {
		l = m.Metadata.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ContentURI)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Checksum != nil {
		l = m.Checksum.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.EncryptionData != nil {
		l = m.EncryptionData.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	if m.DoSign != nil {
		l = m.DoSign.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgShareDocumentResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UUID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendDocumentReceipt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UUID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Sender)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Recipient)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TxHash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.DocumentUUID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.Proof)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSendDocumentReceiptResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.UUID)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgShareDocument) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgShareDocument: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgShareDocument: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipients", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipients = append(m.Recipients, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Metadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Metadata == nil {
				m.Metadata = &DocumentMetadata{}
			}
			if err := m.Metadata.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ContentURI", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ContentURI = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Checksum", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Checksum == nil {
				m.Checksum = &DocumentChecksum{}
			}
			if err := m.Checksum.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptionData", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.EncryptionData == nil {
				m.EncryptionData = &DocumentEncryptionData{}
			}
			if err := m.EncryptionData.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DoSign", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.DoSign == nil {
				m.DoSign = &DocumentDoSign{}
			}
			if err := m.DoSign.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgShareDocumentResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgShareDocumentResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgShareDocumentResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendDocumentReceipt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendDocumentReceipt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendDocumentReceipt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sender", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sender = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Recipient", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Recipient = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxHash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxHash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field DocumentUUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.DocumentUUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proof", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Proof = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSendDocumentReceiptResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSendDocumentReceiptResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSendDocumentReceiptResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UUID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.UUID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
