// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fury/furykyc/genesis.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// GenesisState defines the id module's genesis state.
type GenesisState struct {
	LiquidityPoolAmount     github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=liquidity_pool_amount,json=liquidityPoolAmount,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"liquidity_pool_amount"`
	TrustedServiceProviders []string                                 `protobuf:"bytes,2,rep,name=trusted_service_providers,json=trustedServiceProviders,proto3" json:"trusted_service_providers,omitempty"`
	Invites                 []*Invite                                `protobuf:"bytes,3,rep,name=invites,proto3" json:"invites,omitempty"`
	Memberships             []*Membership                            `protobuf:"bytes,4,rep,name=memberships,proto3" json:"memberships,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_4233dd825a6e47aa, []int{0}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetLiquidityPoolAmount() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.LiquidityPoolAmount
	}
	return nil
}

func (m *GenesisState) GetTrustedServiceProviders() []string {
	if m != nil {
		return m.TrustedServiceProviders
	}
	return nil
}

func (m *GenesisState) GetInvites() []*Invite {
	if m != nil {
		return m.Invites
	}
	return nil
}

func (m *GenesisState) GetMemberships() []*Membership {
	if m != nil {
		return m.Memberships
	}
	return nil
}

func init() {
	proto.RegisterType((*GenesisState)(nil), "tessornetwork.fury.furykyc.GenesisState")
}

func init() { proto.RegisterFile("fury/furykyc/genesis.proto", fileDescriptor_4233dd825a6e47aa) }

var fileDescriptor_4233dd825a6e47aa = []byte{
	// 371 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x91, 0xbf, 0x6e, 0xda, 0x50,
	0x14, 0xc6, 0x6d, 0xa8, 0x5a, 0xd5, 0x74, 0x72, 0x5b, 0xd5, 0x58, 0xaa, 0x41, 0x0c, 0x15, 0x0b,
	0xf7, 0x96, 0x76, 0xab, 0xba, 0x94, 0x0e, 0xb4, 0x43, 0x25, 0x64, 0xb6, 0x2e, 0x96, 0xff, 0xdc,
	0x9a, 0x2b, 0xb0, 0x8f, 0x7b, 0xcf, 0xb5, 0x13, 0x4f, 0x79, 0x85, 0x3c, 0x47, 0x9e, 0x84, 0x11,
	0x29, 0x4b, 0xa6, 0x24, 0x82, 0x17, 0x89, 0x7c, 0x6d, 0x08, 0x0c, 0xc9, 0x62, 0x5f, 0xe9, 0xfb,
	0xbe, 0xdf, 0x39, 0xfa, 0x8e, 0x61, 0xff, 0xcb, 0x45, 0x49, 0xab, 0xcf, 0xb2, 0x0c, 0x69, 0xcc,
	0x52, 0x86, 0x1c, 0x49, 0x26, 0x40, 0x82, 0x69, 0x4b, 0x86, 0x08, 0x22, 0x65, 0xf2, 0x0c, 0xc4,
	0x92, 0x54, 0x26, 0xd2, 0x38, 0xed, 0x77, 0x31, 0xc4, 0xa0, 0x6c, 0xb4, 0x7a, 0xd5, 0x09, 0xfb,
	0xe3, 0x09, 0x2d, 0x61, 0x49, 0xc0, 0x04, 0x2e, 0x78, 0xd6, 0xc8, 0x4e, 0x08, 0x98, 0x00, 0xd2,
	0xc0, 0x47, 0x46, 0x8b, 0x71, 0xc0, 0xa4, 0x3f, 0xa6, 0x21, 0xf0, 0xb4, 0xd6, 0x07, 0xd7, 0x2d,
	0xe3, 0xcd, 0xb4, 0x5e, 0x61, 0x2e, 0x7d, 0xc9, 0xcc, 0x0b, 0xe3, 0xfd, 0x8a, 0xff, 0xcf, 0x79,
	0xc4, 0x65, 0xe9, 0x65, 0x00, 0x2b, 0xcf, 0x4f, 0x20, 0x4f, 0xa5, 0xa5, 0xf7, 0xdb, 0xc3, 0xce,
	0x97, 0x2e, 0xa9, 0x81, 0xa4, 0x02, 0x92, 0x06, 0x48, 0x7e, 0x02, 0x4f, 0x27, 0x9f, 0xd7, 0xb7,
	0x3d, 0xed, 0xea, 0xae, 0x37, 0x8c, 0xb9, 0x5c, 0xe4, 0x01, 0x09, 0x21, 0xa1, 0xcd, 0xf4, 0xfa,
	0x37, 0xc2, 0x68, 0x49, 0x65, 0x99, 0x31, 0x54, 0x01, 0x74, 0xdf, 0x1e, 0x26, 0xcd, 0x00, 0x56,
	0x3f, 0xd4, 0x1c, 0xf3, 0x9b, 0xd1, 0x95, 0x22, 0x47, 0xc9, 0x22, 0x0f, 0x99, 0x28, 0x78, 0xc8,
	0xbc, 0x4c, 0x40, 0xc1, 0x23, 0x26, 0xd0, 0x6a, 0xf5, 0xdb, 0xc3, 0xd7, 0xee, 0x87, 0xc6, 0x30,
	0xaf, 0xf5, 0xd9, 0x5e, 0x36, 0xbf, 0x1b, 0xaf, 0x78, 0x5a, 0x70, 0xc9, 0xd0, 0x6a, 0xab, 0x75,
	0x07, 0xe4, 0xe9, 0x42, 0xc9, 0x6f, 0x65, 0x75, 0xf7, 0x11, 0xf3, 0x97, 0xd1, 0x79, 0xec, 0x0f,
	0xad, 0x17, 0x8a, 0xf0, 0xe9, 0x39, 0xc2, 0x9f, 0x83, 0xdd, 0x3d, 0x8e, 0x4e, 0xa6, 0xeb, 0xad,
	0xa3, 0x6f, 0xb6, 0x8e, 0x7e, 0xbf, 0x75, 0xf4, 0xcb, 0x9d, 0xa3, 0x6d, 0x76, 0x8e, 0x76, 0xb3,
	0x73, 0xb4, 0xbf, 0xa3, 0xa3, 0x72, 0x4e, 0xc0, 0xea, 0x84, 0xf4, 0xfc, 0x70, 0x49, 0xd5, 0x53,
	0xf0, 0x52, 0x5d, 0xe9, 0xeb, 0x43, 0x00, 0x00, 0x00, 0xff, 0xff, 0x24, 0x97, 0xd8, 0x86, 0x34,
	0x02, 0x00, 0x00,
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Memberships) > 0 {
		for iNdEx := len(m.Memberships) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Memberships[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.Invites) > 0 {
		for iNdEx := len(m.Invites) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Invites[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.TrustedServiceProviders) > 0 {
		for iNdEx := len(m.TrustedServiceProviders) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.TrustedServiceProviders[iNdEx])
			copy(dAtA[i:], m.TrustedServiceProviders[iNdEx])
			i = encodeVarintGenesis(dAtA, i, uint64(len(m.TrustedServiceProviders[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.LiquidityPoolAmount) > 0 {
		for iNdEx := len(m.LiquidityPoolAmount) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.LiquidityPoolAmount[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenesis(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintGenesis(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenesis(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.LiquidityPoolAmount) > 0 {
		for _, e := range m.LiquidityPoolAmount {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.TrustedServiceProviders) > 0 {
		for _, s := range m.TrustedServiceProviders {
			l = len(s)
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Invites) > 0 {
		for _, e := range m.Invites {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	if len(m.Memberships) > 0 {
		for _, e := range m.Memberships {
			l = e.Size()
			n += 1 + l + sovGenesis(uint64(l))
		}
	}
	return n
}

func sovGenesis(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenesis(x uint64) (n int) {
	return sovGenesis(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidityPoolAmount", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.LiquidityPoolAmount = append(m.LiquidityPoolAmount, types.Coin{})
			if err := m.LiquidityPoolAmount[len(m.LiquidityPoolAmount)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrustedServiceProviders", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TrustedServiceProviders = append(m.TrustedServiceProviders, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invites", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invites = append(m.Invites, &Invite{})
			if err := m.Invites[len(m.Invites)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memberships", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenesis
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenesis
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memberships = append(m.Memberships, &Membership{})
			if err := m.Memberships[len(m.Memberships)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenesis(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthGenesis
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenesis(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenesis
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenesis
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenesis
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenesis
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenesis
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenesis        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenesis          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenesis = fmt.Errorf("proto: unexpected end of group")
)
