// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fury/furykyc/query.proto

package types

import (
	context "context"
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryInvitesRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryInvitesRequest) Reset()         { *m = QueryInvitesRequest{} }
func (m *QueryInvitesRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInvitesRequest) ProtoMessage()    {}
func (*QueryInvitesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{0}
}
func (m *QueryInvitesRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInvitesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInvitesRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInvitesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInvitesRequest.Merge(m, src)
}
func (m *QueryInvitesRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInvitesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInvitesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInvitesRequest proto.InternalMessageInfo

func (m *QueryInvitesRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryInvitesResponse struct {
	Invites    []*Invite           `protobuf:"bytes,1,rep,name=invites,proto3" json:"invites,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryInvitesResponse) Reset()         { *m = QueryInvitesResponse{} }
func (m *QueryInvitesResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInvitesResponse) ProtoMessage()    {}
func (*QueryInvitesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{1}
}
func (m *QueryInvitesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInvitesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInvitesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInvitesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInvitesResponse.Merge(m, src)
}
func (m *QueryInvitesResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInvitesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInvitesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInvitesResponse proto.InternalMessageInfo

func (m *QueryInvitesResponse) GetInvites() []*Invite {
	if m != nil {
		return m.Invites
	}
	return nil
}

func (m *QueryInvitesResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryInviteRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryInviteRequest) Reset()         { *m = QueryInviteRequest{} }
func (m *QueryInviteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryInviteRequest) ProtoMessage()    {}
func (*QueryInviteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{2}
}
func (m *QueryInviteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInviteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInviteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInviteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInviteRequest.Merge(m, src)
}
func (m *QueryInviteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryInviteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInviteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInviteRequest proto.InternalMessageInfo

func (m *QueryInviteRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryInviteResponse struct {
	Invite *Invite `protobuf:"bytes,1,opt,name=invite,proto3" json:"invite,omitempty"`
}

func (m *QueryInviteResponse) Reset()         { *m = QueryInviteResponse{} }
func (m *QueryInviteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryInviteResponse) ProtoMessage()    {}
func (*QueryInviteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{3}
}
func (m *QueryInviteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryInviteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryInviteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryInviteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryInviteResponse.Merge(m, src)
}
func (m *QueryInviteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryInviteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryInviteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryInviteResponse proto.InternalMessageInfo

func (m *QueryInviteResponse) GetInvite() *Invite {
	if m != nil {
		return m.Invite
	}
	return nil
}

type QueryTspsRequest struct {
}

func (m *QueryTspsRequest) Reset()         { *m = QueryTspsRequest{} }
func (m *QueryTspsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTspsRequest) ProtoMessage()    {}
func (*QueryTspsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{4}
}
func (m *QueryTspsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTspsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTspsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTspsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTspsRequest.Merge(m, src)
}
func (m *QueryTspsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTspsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTspsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTspsRequest proto.InternalMessageInfo

type QueryTspsResponse struct {
	Tsps []string `protobuf:"bytes,1,rep,name=tsps,proto3" json:"tsps,omitempty"`
}

func (m *QueryTspsResponse) Reset()         { *m = QueryTspsResponse{} }
func (m *QueryTspsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTspsResponse) ProtoMessage()    {}
func (*QueryTspsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{5}
}
func (m *QueryTspsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTspsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTspsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTspsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTspsResponse.Merge(m, src)
}
func (m *QueryTspsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTspsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTspsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTspsResponse proto.InternalMessageInfo

func (m *QueryTspsResponse) GetTsps() []string {
	if m != nil {
		return m.Tsps
	}
	return nil
}

type QueryMembershipsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMembershipsRequest) Reset()         { *m = QueryMembershipsRequest{} }
func (m *QueryMembershipsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMembershipsRequest) ProtoMessage()    {}
func (*QueryMembershipsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{6}
}
func (m *QueryMembershipsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMembershipsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMembershipsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMembershipsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMembershipsRequest.Merge(m, src)
}
func (m *QueryMembershipsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMembershipsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMembershipsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMembershipsRequest proto.InternalMessageInfo

func (m *QueryMembershipsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMembershipsResponse struct {
	Memberships []*Membership       `protobuf:"bytes,1,rep,name=memberships,proto3" json:"memberships,omitempty"`
	Pagination  *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryMembershipsResponse) Reset()         { *m = QueryMembershipsResponse{} }
func (m *QueryMembershipsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMembershipsResponse) ProtoMessage()    {}
func (*QueryMembershipsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{7}
}
func (m *QueryMembershipsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMembershipsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMembershipsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMembershipsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMembershipsResponse.Merge(m, src)
}
func (m *QueryMembershipsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMembershipsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMembershipsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMembershipsResponse proto.InternalMessageInfo

func (m *QueryMembershipsResponse) GetMemberships() []*Membership {
	if m != nil {
		return m.Memberships
	}
	return nil
}

func (m *QueryMembershipsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryMembershipRequest struct {
	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (m *QueryMembershipRequest) Reset()         { *m = QueryMembershipRequest{} }
func (m *QueryMembershipRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMembershipRequest) ProtoMessage()    {}
func (*QueryMembershipRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{8}
}
func (m *QueryMembershipRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMembershipRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMembershipRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMembershipRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMembershipRequest.Merge(m, src)
}
func (m *QueryMembershipRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMembershipRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMembershipRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMembershipRequest proto.InternalMessageInfo

func (m *QueryMembershipRequest) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

type QueryMembershipResponse struct {
	Membership *Membership `protobuf:"bytes,1,opt,name=membership,proto3" json:"membership,omitempty"`
}

func (m *QueryMembershipResponse) Reset()         { *m = QueryMembershipResponse{} }
func (m *QueryMembershipResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMembershipResponse) ProtoMessage()    {}
func (*QueryMembershipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{9}
}
func (m *QueryMembershipResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMembershipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMembershipResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMembershipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMembershipResponse.Merge(m, src)
}
func (m *QueryMembershipResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMembershipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMembershipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMembershipResponse proto.InternalMessageInfo

func (m *QueryMembershipResponse) GetMembership() *Membership {
	if m != nil {
		return m.Membership
	}
	return nil
}

type QueryFundsRequest struct {
}

func (m *QueryFundsRequest) Reset()         { *m = QueryFundsRequest{} }
func (m *QueryFundsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryFundsRequest) ProtoMessage()    {}
func (*QueryFundsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{10}
}
func (m *QueryFundsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFundsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFundsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFundsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFundsRequest.Merge(m, src)
}
func (m *QueryFundsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryFundsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFundsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFundsRequest proto.InternalMessageInfo

type QueryFundsResponse struct {
	Funds github_com_cosmos_cosmos_sdk_types.Coins `protobuf:"bytes,1,rep,name=funds,proto3,castrepeated=github.com/cosmos/cosmos-sdk/types.Coins" json:"funds"`
}

func (m *QueryFundsResponse) Reset()         { *m = QueryFundsResponse{} }
func (m *QueryFundsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryFundsResponse) ProtoMessage()    {}
func (*QueryFundsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_2f4d9a13ba8864d3, []int{11}
}
func (m *QueryFundsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryFundsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryFundsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryFundsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryFundsResponse.Merge(m, src)
}
func (m *QueryFundsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryFundsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryFundsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryFundsResponse proto.InternalMessageInfo

func (m *QueryFundsResponse) GetFunds() github_com_cosmos_cosmos_sdk_types.Coins {
	if m != nil {
		return m.Funds
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryInvitesRequest)(nil), "tessornetwork.fury.furykyc.QueryInvitesRequest")
	proto.RegisterType((*QueryInvitesResponse)(nil), "tessornetwork.fury.furykyc.QueryInvitesResponse")
	proto.RegisterType((*QueryInviteRequest)(nil), "tessornetwork.fury.furykyc.QueryInviteRequest")
	proto.RegisterType((*QueryInviteResponse)(nil), "tessornetwork.fury.furykyc.QueryInviteResponse")
	proto.RegisterType((*QueryTspsRequest)(nil), "tessornetwork.fury.furykyc.QueryTspsRequest")
	proto.RegisterType((*QueryTspsResponse)(nil), "tessornetwork.fury.furykyc.QueryTspsResponse")
	proto.RegisterType((*QueryMembershipsRequest)(nil), "tessornetwork.fury.furykyc.QueryMembershipsRequest")
	proto.RegisterType((*QueryMembershipsResponse)(nil), "tessornetwork.fury.furykyc.QueryMembershipsResponse")
	proto.RegisterType((*QueryMembershipRequest)(nil), "tessornetwork.fury.furykyc.QueryMembershipRequest")
	proto.RegisterType((*QueryMembershipResponse)(nil), "tessornetwork.fury.furykyc.QueryMembershipResponse")
	proto.RegisterType((*QueryFundsRequest)(nil), "tessornetwork.fury.furykyc.QueryFundsRequest")
	proto.RegisterType((*QueryFundsResponse)(nil), "tessornetwork.fury.furykyc.QueryFundsResponse")
}

func init() { proto.RegisterFile("fury/furykyc/query.proto", fileDescriptor_2f4d9a13ba8864d3) }

var fileDescriptor_2f4d9a13ba8864d3 = []byte{
	// 711 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0xc1, 0x4f, 0xd4, 0x4e,
	0x14, 0xc7, 0x77, 0xf8, 0xc1, 0x12, 0xde, 0x5e, 0x7e, 0x0e, 0x20, 0x4b, 0x91, 0x82, 0x8d, 0x01,
	0x42, 0x64, 0x06, 0x16, 0x4f, 0xc6, 0x13, 0x26, 0xa0, 0x07, 0x13, 0x69, 0x3c, 0x99, 0x78, 0xe8,
	0xee, 0x0e, 0xa5, 0xc1, 0xed, 0x94, 0x4e, 0x17, 0xdc, 0x18, 0x63, 0xa2, 0x47, 0x2f, 0x1a, 0x8f,
	0xc6, 0x83, 0x57, 0x13, 0xff, 0x0f, 0x8e, 0x24, 0x5e, 0x3c, 0xa9, 0x01, 0xff, 0x02, 0xff, 0x02,
	0xd3, 0x99, 0xe9, 0xb6, 0x75, 0x5d, 0xb6, 0x9b, 0x70, 0x81, 0x32, 0xbc, 0xef, 0xfb, 0x7e, 0xde,
	0x7b, 0xf3, 0x5a, 0xa8, 0xee, 0xb5, 0xc3, 0x0e, 0x8d, 0x7f, 0x1c, 0x74, 0x1a, 0xf4, 0xb0, 0xcd,
	0xc2, 0x0e, 0x09, 0x42, 0x1e, 0x71, 0x6c, 0x44, 0x4c, 0x08, 0x1e, 0xfa, 0x2c, 0x3a, 0xe6, 0xe1,
	0x01, 0x89, 0x43, 0x88, 0x8e, 0x33, 0xae, 0xb9, 0x9c, 0xbb, 0x4f, 0x19, 0x75, 0x02, 0x8f, 0x3a,
	0xbe, 0xcf, 0x23, 0x27, 0xf2, 0xb8, 0x2f, 0x94, 0xd2, 0x58, 0x6d, 0x70, 0xd1, 0xe2, 0x82, 0xd6,
	0x1d, 0xc1, 0x54, 0x4a, 0x7a, 0xb4, 0x51, 0x67, 0x91, 0xb3, 0x41, 0x03, 0xc7, 0xf5, 0x7c, 0x19,
	0xac, 0x63, 0xe7, 0x73, 0xfe, 0x2d, 0xd6, 0xaa, 0xb3, 0x50, 0xec, 0x7b, 0x81, 0xfe, 0xb7, 0x99,
	0x4d, 0x95, 0x24, 0x69, 0x70, 0x2f, 0x91, 0x4f, 0xb9, 0xdc, 0xe5, 0xf2, 0x91, 0xc6, 0x4f, 0xea,
	0xd4, 0x7a, 0x02, 0x93, 0xbb, 0xb1, 0xed, 0x7d, 0xff, 0xc8, 0x8b, 0x98, 0xb0, 0xd9, 0x61, 0x9b,
	0x89, 0x08, 0x6f, 0x03, 0xa4, 0xfe, 0x55, 0xb4, 0x88, 0x56, 0x2a, 0xb5, 0x25, 0xa2, 0x1c, 0x48,
	0xec, 0x40, 0x54, 0xfd, 0xda, 0x87, 0x3c, 0x74, 0x5c, 0xa6, 0xb5, 0x76, 0x46, 0x69, 0x7d, 0x44,
	0x30, 0x95, 0xcf, 0x2f, 0x02, 0xee, 0x0b, 0x86, 0xef, 0xc0, 0xb8, 0xa7, 0x8e, 0xaa, 0x68, 0xf1,
	0xbf, 0x95, 0x4a, 0xcd, 0x22, 0xfd, 0x9b, 0x48, 0x94, 0xda, 0x4e, 0x24, 0x78, 0x27, 0x87, 0x37,
	0x22, 0xf1, 0x96, 0x07, 0xe2, 0x29, 0xeb, 0x1c, 0x1f, 0x01, 0x9c, 0xc1, 0x4b, 0xaa, 0xaf, 0xc2,
	0xb8, 0xd3, 0x6c, 0x86, 0x4c, 0x08, 0x59, 0xfa, 0x84, 0x9d, 0xfc, 0x69, 0xed, 0xe6, 0xda, 0xd5,
	0xad, 0xe6, 0x36, 0x94, 0x15, 0x9a, 0x6e, 0x55, 0x91, 0x62, 0xb4, 0xc2, 0xc2, 0xf0, 0xbf, 0x4c,
	0xf9, 0x48, 0x04, 0x49, 0xfb, 0xad, 0x65, 0xb8, 0x92, 0x39, 0xd3, 0x26, 0x18, 0x46, 0x23, 0x11,
	0xa8, 0x7e, 0x4d, 0xd8, 0xf2, 0xd9, 0x72, 0x60, 0x46, 0x06, 0x3e, 0xe8, 0xde, 0x86, 0x4b, 0x1f,
	0xe1, 0x17, 0x04, 0xd5, 0x5e, 0x0f, 0xcd, 0x74, 0x0f, 0x2a, 0xe9, 0x45, 0x4c, 0x46, 0xb9, 0x74,
	0x51, 0xf5, 0x69, 0x16, 0x3b, 0x2b, 0xbd, 0xbc, 0x91, 0xd6, 0xe0, 0xea, 0x5f, 0xb8, 0x83, 0xc7,
	0xda, 0xdb, 0xc6, 0x6e, 0x85, 0xdb, 0x00, 0x29, 0x66, 0xb7, 0x8d, 0xc5, 0x0a, 0xcc, 0x28, 0xad,
	0x49, 0x3d, 0xd2, 0xed, 0xb6, 0xdf, 0xec, 0xce, 0xf9, 0x58, 0x5f, 0x3f, 0x7d, 0xa8, 0x2d, 0x1d,
	0x18, 0xdb, 0x8b, 0x0f, 0x74, 0x3b, 0x67, 0x73, 0x5d, 0x48, 0xea, 0xbf, 0xcb, 0x3d, 0x7f, 0x6b,
	0xfd, 0xe4, 0xfb, 0x42, 0xe9, 0xf3, 0x8f, 0x85, 0x15, 0xd7, 0x8b, 0xf6, 0xdb, 0x75, 0xd2, 0xe0,
	0x2d, 0xaa, 0x5f, 0x03, 0xea, 0xd7, 0x9a, 0x68, 0x1e, 0xd0, 0xa8, 0x13, 0x30, 0x21, 0x05, 0xc2,
	0x56, 0x99, 0x6b, 0xbf, 0xcb, 0x30, 0x26, 0x9d, 0xf1, 0x1b, 0x04, 0xe3, 0x7a, 0x39, 0x31, 0xbd,
	0xa8, 0xae, 0x7f, 0xbc, 0x26, 0x8c, 0xf5, 0xe2, 0x02, 0x55, 0x9b, 0x35, 0xff, 0xea, 0xeb, 0xaf,
	0xf7, 0x23, 0x33, 0x78, 0x9a, 0xe6, 0xde, 0x66, 0xc9, 0x62, 0xbf, 0x43, 0x50, 0x56, 0x12, 0x4c,
	0x0a, 0xe6, 0x4e, 0x58, 0x68, 0xe1, 0x78, 0x8d, 0xb2, 0x24, 0x51, 0x16, 0xb1, 0x99, 0x47, 0x79,
	0xae, 0x2f, 0xc5, 0x0b, 0x0d, 0x85, 0x5f, 0xc2, 0x68, 0xbc, 0x87, 0xf8, 0xe6, 0x40, 0x83, 0xcc,
	0x0a, 0x1b, 0x6b, 0x05, 0xa3, 0x35, 0x8c, 0x21, 0x61, 0xa6, 0x30, 0xce, 0xc3, 0xc4, 0x4b, 0x8e,
	0x3f, 0x20, 0xa8, 0x64, 0x96, 0x0f, 0x6f, 0x0e, 0x4c, 0xdd, 0xfb, 0x3a, 0x30, 0x6e, 0x0d, 0x27,
	0xd2, 0x58, 0xd7, 0x25, 0xd6, 0x1c, 0x9e, 0xa5, 0x7d, 0x3e, 0x3e, 0x02, 0x7f, 0x42, 0x00, 0xa9,
	0x14, 0xd7, 0x86, 0xf0, 0x49, 0xd8, 0x36, 0x87, 0xd2, 0x68, 0xb4, 0x55, 0x89, 0x76, 0x03, 0x5b,
	0xfd, 0xc6, 0x97, 0x42, 0xe2, 0xd7, 0x08, 0xc6, 0xe4, 0x8e, 0xe1, 0xc1, 0x63, 0xc9, 0x2e, 0xa8,
	0x41, 0x8a, 0x86, 0x6b, 0xa8, 0x39, 0x09, 0x35, 0x8d, 0x27, 0xf3, 0x50, 0x72, 0xe9, 0xb6, 0x76,
	0x4e, 0xce, 0x4c, 0x74, 0x7a, 0x66, 0xa2, 0x9f, 0x67, 0x26, 0x7a, 0x7b, 0x6e, 0x96, 0x4e, 0xcf,
	0xcd, 0xd2, 0xb7, 0x73, 0xb3, 0xf4, 0x78, 0x2d, 0xb3, 0xbf, 0x39, 0x43, 0x95, 0xe6, 0x59, 0x7a,
	0x1f, 0xe2, 0x55, 0xae, 0x97, 0xe5, 0xb7, 0x7b, 0xf3, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0xdb,
	0x97, 0x80, 0x0e, 0x92, 0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries all invites
	Invites(ctx context.Context, in *QueryInvitesRequest, opts ...grpc.CallOption) (*QueryInvitesResponse, error)
	// Queries a invite by address
	Invite(ctx context.Context, in *QueryInviteRequest, opts ...grpc.CallOption) (*QueryInviteResponse, error)
	// Queries a ivite by id.
	// Queries all Tsp.
	Tsps(ctx context.Context, in *QueryTspsRequest, opts ...grpc.CallOption) (*QueryTspsResponse, error)
	// Queries all memberships
	Memberships(ctx context.Context, in *QueryMembershipsRequest, opts ...grpc.CallOption) (*QueryMembershipsResponse, error)
	// Queries a membership by address
	Membership(ctx context.Context, in *QueryMembershipRequest, opts ...grpc.CallOption) (*QueryMembershipResponse, error)
	// Queries funds of ABR
	Funds(ctx context.Context, in *QueryFundsRequest, opts ...grpc.CallOption) (*QueryFundsResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Invites(ctx context.Context, in *QueryInvitesRequest, opts ...grpc.CallOption) (*QueryInvitesResponse, error) {
	out := new(QueryInvitesResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.furykyc.Query/Invites", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Invite(ctx context.Context, in *QueryInviteRequest, opts ...grpc.CallOption) (*QueryInviteResponse, error) {
	out := new(QueryInviteResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.furykyc.Query/Invite", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Tsps(ctx context.Context, in *QueryTspsRequest, opts ...grpc.CallOption) (*QueryTspsResponse, error) {
	out := new(QueryTspsResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.furykyc.Query/Tsps", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Memberships(ctx context.Context, in *QueryMembershipsRequest, opts ...grpc.CallOption) (*QueryMembershipsResponse, error) {
	out := new(QueryMembershipsResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.furykyc.Query/Memberships", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Membership(ctx context.Context, in *QueryMembershipRequest, opts ...grpc.CallOption) (*QueryMembershipResponse, error) {
	out := new(QueryMembershipResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.furykyc.Query/Membership", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Funds(ctx context.Context, in *QueryFundsRequest, opts ...grpc.CallOption) (*QueryFundsResponse, error) {
	out := new(QueryFundsResponse)
	err := c.cc.Invoke(ctx, "/tessornetwork.fury.furykyc.Query/Funds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries all invites
	Invites(context.Context, *QueryInvitesRequest) (*QueryInvitesResponse, error)
	// Queries a invite by address
	Invite(context.Context, *QueryInviteRequest) (*QueryInviteResponse, error)
	// Queries a ivite by id.
	// Queries all Tsp.
	Tsps(context.Context, *QueryTspsRequest) (*QueryTspsResponse, error)
	// Queries all memberships
	Memberships(context.Context, *QueryMembershipsRequest) (*QueryMembershipsResponse, error)
	// Queries a membership by address
	Membership(context.Context, *QueryMembershipRequest) (*QueryMembershipResponse, error)
	// Queries funds of ABR
	Funds(context.Context, *QueryFundsRequest) (*QueryFundsResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Invites(ctx context.Context, req *QueryInvitesRequest) (*QueryInvitesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invites not implemented")
}
func (*UnimplementedQueryServer) Invite(ctx context.Context, req *QueryInviteRequest) (*QueryInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Invite not implemented")
}
func (*UnimplementedQueryServer) Tsps(ctx context.Context, req *QueryTspsRequest) (*QueryTspsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Tsps not implemented")
}
func (*UnimplementedQueryServer) Memberships(ctx context.Context, req *QueryMembershipsRequest) (*QueryMembershipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Memberships not implemented")
}
func (*UnimplementedQueryServer) Membership(ctx context.Context, req *QueryMembershipRequest) (*QueryMembershipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Membership not implemented")
}
func (*UnimplementedQueryServer) Funds(ctx context.Context, req *QueryFundsRequest) (*QueryFundsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Funds not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Invites_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInvitesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Invites(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.furykyc.Query/Invites",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Invites(ctx, req.(*QueryInvitesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Invite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Invite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.furykyc.Query/Invite",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Invite(ctx, req.(*QueryInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Tsps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTspsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Tsps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.furykyc.Query/Tsps",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Tsps(ctx, req.(*QueryTspsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Memberships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMembershipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Memberships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.furykyc.Query/Memberships",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Memberships(ctx, req.(*QueryMembershipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Membership_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMembershipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Membership(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.furykyc.Query/Membership",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Membership(ctx, req.(*QueryMembershipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Funds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFundsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Funds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tessornetwork.fury.furykyc.Query/Funds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Funds(ctx, req.(*QueryFundsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tessornetwork.fury.furykyc.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Invites",
			Handler:    _Query_Invites_Handler,
		},
		{
			MethodName: "Invite",
			Handler:    _Query_Invite_Handler,
		},
		{
			MethodName: "Tsps",
			Handler:    _Query_Tsps_Handler,
		},
		{
			MethodName: "Memberships",
			Handler:    _Query_Memberships_Handler,
		},
		{
			MethodName: "Membership",
			Handler:    _Query_Membership_Handler,
		},
		{
			MethodName: "Funds",
			Handler:    _Query_Funds_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fury/furykyc/query.proto",
}

func (m *QueryInvitesRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInvitesRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInvitesRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInvitesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInvitesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInvitesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Invites) > 0 {
		for iNdEx := len(m.Invites) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Invites[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryInviteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInviteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInviteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryInviteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryInviteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryInviteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Invite != nil {
		{
			size, err := m.Invite.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTspsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTspsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTspsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryTspsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTspsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTspsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Tsps) > 0 {
		for iNdEx := len(m.Tsps) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Tsps[iNdEx])
			copy(dAtA[i:], m.Tsps[iNdEx])
			i = encodeVarintQuery(dAtA, i, uint64(len(m.Tsps[iNdEx])))
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryMembershipsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMembershipsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMembershipsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMembershipsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMembershipsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMembershipsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Memberships) > 0 {
		for iNdEx := len(m.Memberships) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Memberships[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryMembershipRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMembershipRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMembershipRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Address) > 0 {
		i -= len(m.Address)
		copy(dAtA[i:], m.Address)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Address)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMembershipResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMembershipResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMembershipResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Membership != nil {
		{
			size, err := m.Membership.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryFundsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFundsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFundsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryFundsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryFundsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryFundsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Funds) > 0 {
		for iNdEx := len(m.Funds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Funds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryInvitesRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInvitesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Invites) > 0 {
		for _, e := range m.Invites {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInviteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryInviteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Invite != nil {
		l = m.Invite.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTspsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryTspsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Tsps) > 0 {
		for _, s := range m.Tsps {
			l = len(s)
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryMembershipsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMembershipsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Memberships) > 0 {
		for _, e := range m.Memberships {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMembershipRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Address)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMembershipResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Membership != nil {
		l = m.Membership.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryFundsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryFundsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Funds) > 0 {
		for _, e := range m.Funds {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryInvitesRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInvitesRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInvitesRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInvitesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInvitesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInvitesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invites", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Invites = append(m.Invites, &Invite{})
			if err := m.Invites[len(m.Invites)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInviteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInviteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInviteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryInviteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryInviteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryInviteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Invite", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Invite == nil {
				m.Invite = &Invite{}
			}
			if err := m.Invite.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTspsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTspsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTspsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTspsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTspsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTspsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Tsps", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Tsps = append(m.Tsps, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMembershipsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMembershipsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMembershipsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMembershipsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMembershipsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMembershipsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Memberships", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Memberships = append(m.Memberships, &Membership{})
			if err := m.Memberships[len(m.Memberships)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMembershipRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMembershipRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMembershipRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Address", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Address = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMembershipResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMembershipResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMembershipResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Membership", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Membership == nil {
				m.Membership = &Membership{}
			}
			if err := m.Membership.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFundsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFundsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFundsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryFundsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryFundsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryFundsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Funds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Funds = append(m.Funds, types.Coin{})
			if err := m.Funds[len(m.Funds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
