// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: fury/furymint/position.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	github_com_gogo_protobuf_types "github.com/gogo/protobuf/types"
	_ "google.golang.org/protobuf/types/known/durationpb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	io "io"
	math "math"
	math_bits "math/bits"
	time "time"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf
var _ = time.Kitchen

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Position struct {
	Owner        string                                 `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Collateral   int64                                  `protobuf:"varint,2,opt,name=collateral,proto3" json:"collateral,omitempty"`
	Credits      *types.Coin                            `protobuf:"bytes,3,opt,name=credits,proto3" json:"credits,omitempty"`
	CreatedAt    *time.Time                             `protobuf:"bytes,4,opt,name=created_at,json=createdAt,proto3,stdtime" json:"created_at,omitempty"`
	ID           string                                 `protobuf:"bytes,5,opt,name=ID,proto3" json:"ID,omitempty"`
	ExchangeRate github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=exchange_rate,json=exchangeRate,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"exchange_rate"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_ca296584be47c78a, []int{0}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Position.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return m.Size()
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Position) GetCollateral() int64 {
	if m != nil {
		return m.Collateral
	}
	return 0
}

func (m *Position) GetCredits() *types.Coin {
	if m != nil {
		return m.Credits
	}
	return nil
}

func (m *Position) GetCreatedAt() *time.Time {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *Position) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func init() {
	proto.RegisterType((*Position)(nil), "tessornetwork.fury.furymint.Position")
}

func init() { proto.RegisterFile("fury/furymint/position.proto", fileDescriptor_ca296584be47c78a) }

var fileDescriptor_ca296584be47c78a = []byte{
	// 384 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x52, 0xcd, 0x6e, 0xd4, 0x30,
	0x10, 0x5e, 0xa7, 0x3f, 0x50, 0xf3, 0x73, 0x88, 0x7a, 0x08, 0x01, 0x39, 0x2b, 0x0e, 0x68, 0x2f,
	0xd8, 0x2a, 0x7d, 0x00, 0xc4, 0xb2, 0x07, 0x7a, 0x43, 0x81, 0x13, 0x97, 0xca, 0x71, 0xa6, 0xa9,
	0xd5, 0x24, 0x13, 0xd9, 0x13, 0xda, 0xbe, 0x45, 0xef, 0xbc, 0x50, 0x8f, 0x3d, 0x22, 0x0e, 0x05,
	0xed, 0xbe, 0x08, 0xca, 0x9f, 0xba, 0x70, 0xb1, 0x3d, 0x9e, 0x6f, 0xbe, 0x6f, 0x3e, 0x8f, 0xf9,
	0xab, 0xb3, 0xd6, 0x5d, 0xab, 0x6e, 0xa9, 0x6c, 0x4d, 0xaa, 0x41, 0x6f, 0xc9, 0x62, 0x2d, 0x1b,
	0x87, 0x84, 0xe1, 0x4b, 0x02, 0xef, 0xd1, 0xd5, 0x40, 0x97, 0xe8, 0x2e, 0x64, 0x07, 0x93, 0x13,
	0x36, 0x3e, 0x2c, 0xb0, 0xc0, 0x1e, 0xa7, 0xba, 0xd3, 0x50, 0x12, 0x27, 0x05, 0x62, 0x51, 0x82,
	0xea, 0xa3, 0xac, 0x3d, 0x53, 0x64, 0x2b, 0xf0, 0xa4, 0xab, 0x66, 0x04, 0x88, 0xff, 0x01, 0x79,
	0xeb, 0xf4, 0x83, 0x66, 0x2c, 0x0c, 0xfa, 0x0a, 0xbd, 0xca, 0xb4, 0x07, 0xf5, 0xfd, 0x28, 0x03,
	0xd2, 0x47, 0xca, 0xa0, 0x1d, 0xf3, 0xaf, 0x7f, 0x04, 0xfc, 0xf1, 0xe7, 0xb1, 0xcd, 0xf0, 0x90,
	0xef, 0xe1, 0x65, 0x0d, 0x2e, 0x62, 0x73, 0xb6, 0x38, 0x48, 0x87, 0x20, 0x14, 0x9c, 0x1b, 0x2c,
	0x4b, 0x4d, 0xe0, 0x74, 0x19, 0x05, 0x73, 0xb6, 0xd8, 0x49, 0xb7, 0x6e, 0xc2, 0x63, 0xfe, 0xc8,
	0x38, 0xc8, 0x2d, 0xf9, 0x68, 0x67, 0xce, 0x16, 0x4f, 0xde, 0xbd, 0x90, 0x83, 0xa8, 0xec, 0x44,
	0xe5, 0x28, 0x2a, 0x3f, 0xa2, 0xad, 0xd3, 0x09, 0x19, 0xbe, 0xe7, 0xdc, 0x38, 0xd0, 0x04, 0xf9,
	0xa9, 0xa6, 0x68, 0xb7, 0xaf, 0x8b, 0xe5, 0x60, 0x46, 0x4e, 0x66, 0xe4, 0xd7, 0xc9, 0xed, 0x72,
	0xf7, 0xe6, 0x77, 0xc2, 0xd2, 0x83, 0xb1, 0xe6, 0x03, 0x85, 0xcf, 0x79, 0x70, 0xb2, 0x8a, 0xf6,
	0xfa, 0x46, 0x83, 0x93, 0x55, 0xf8, 0x85, 0x3f, 0x83, 0x2b, 0x73, 0xae, 0xeb, 0x02, 0x4e, 0x9d,
	0x26, 0x88, 0xf6, 0xbb, 0xd4, 0x52, 0xde, 0xde, 0x27, 0xb3, 0x5f, 0xf7, 0xc9, 0x9b, 0xc2, 0xd2,
	0x79, 0x9b, 0x49, 0x83, 0x95, 0x1a, 0x9f, 0x64, 0xd8, 0xde, 0xfa, 0xfc, 0x42, 0xd1, 0x75, 0x03,
	0x5e, 0xae, 0xc0, 0xa4, 0x4f, 0x27, 0x92, 0x54, 0x13, 0x2c, 0x3f, 0xdd, 0xae, 0x05, 0xbb, 0x5b,
	0x0b, 0xf6, 0x67, 0x2d, 0xd8, 0xcd, 0x46, 0xcc, 0xee, 0x36, 0x62, 0xf6, 0x73, 0x23, 0x66, 0xdf,
	0xe4, 0x16, 0xdf, 0x3f, 0x63, 0xed, 0xa7, 0xaf, 0xae, 0x1e, 0x3e, 0x41, 0xcf, 0x9d, 0xed, 0xf7,
	0x9e, 0x8e, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x43, 0x7a, 0x8b, 0xe4, 0x22, 0x02, 0x00, 0x00,
}

func (m *Position) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Position) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Position) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.ExchangeRate.Size()
		i -= size
		if _, err := m.ExchangeRate.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintPosition(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	if len(m.ID) > 0 {
		i -= len(m.ID)
		copy(dAtA[i:], m.ID)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.ID)))
		i--
		dAtA[i] = 0x2a
	}
	if m.CreatedAt != nil {
		n1, err1 := github_com_gogo_protobuf_types.StdTimeMarshalTo(*m.CreatedAt, dAtA[i-github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt):])
		if err1 != nil {
			return 0, err1
		}
		i -= n1
		i = encodeVarintPosition(dAtA, i, uint64(n1))
		i--
		dAtA[i] = 0x22
	}
	if m.Credits != nil {
		{
			size, err := m.Credits.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintPosition(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if m.Collateral != 0 {
		i = encodeVarintPosition(dAtA, i, uint64(m.Collateral))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Owner) > 0 {
		i -= len(m.Owner)
		copy(dAtA[i:], m.Owner)
		i = encodeVarintPosition(dAtA, i, uint64(len(m.Owner)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintPosition(dAtA []byte, offset int, v uint64) int {
	offset -= sovPosition(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Position) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Owner)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	if m.Collateral != 0 {
		n += 1 + sovPosition(uint64(m.Collateral))
	}
	if m.Credits != nil {
		l = m.Credits.Size()
		n += 1 + l + sovPosition(uint64(l))
	}
	if m.CreatedAt != nil {
		l = github_com_gogo_protobuf_types.SizeOfStdTime(*m.CreatedAt)
		n += 1 + l + sovPosition(uint64(l))
	}
	l = len(m.ID)
	if l > 0 {
		n += 1 + l + sovPosition(uint64(l))
	}
	l = m.ExchangeRate.Size()
	n += 1 + l + sovPosition(uint64(l))
	return n
}

func sovPosition(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozPosition(x uint64) (n int) {
	return sovPosition(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Position) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowPosition
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Position: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Position: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Owner", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Owner = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Collateral", wireType)
			}
			m.Collateral = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Collateral |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Credits", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Credits == nil {
				m.Credits = &types.Coin{}
			}
			if err := m.Credits.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreatedAt", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.CreatedAt == nil {
				m.CreatedAt = new(time.Time)
			}
			if err := github_com_gogo_protobuf_types.StdTimeUnmarshal(m.CreatedAt, dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ID", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ID = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangeRate", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthPosition
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthPosition
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExchangeRate.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipPosition(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthPosition
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipPosition(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowPosition
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowPosition
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthPosition
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupPosition
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthPosition
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthPosition        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowPosition          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupPosition = fmt.Errorf("proto: unexpected end of group")
)
